### ISSUE TITLE
PutleBot Loader

### ISSUE THREAD

**Issue by gjersvik** [equinor/robogamer#16]
Have an over the air updater that where bots on boot ask the service what software it should run.
* Be able to have different artifacts.
* Be able to configure each bot at when its starts up.
* Be able to remotely trigger and update / reboot of bot(s).

- [ ] Setup embedded environment. #22 
- [ ] Find rust web framework. #23
- [ ] OTA upgrade prof of concept. #24
- [ ] Spec out the rest of this epic. #25

**Comment by gjersvik** [comment]
Closed for archive.
